from system.lib.java import JavaClass

Array = JavaClass("java.lang.reflect.Array")
Clazz = JavaClass("java.lang.Class")
Float = JavaClass("java.lang.Float")
Thread = JavaClass("java.lang.Thread")
Minescript = JavaClass("net.minescript.common.Minescript")
Minecraft = JavaClass("net.minecraft.client.Minecraft")
ClickType = JavaClass("net.minecraft.world.inventory.ClickType")
Component = JavaClass("net.minecraft.network.chat.Component")
KeyMapping = JavaClass("net.minecraft.client.KeyMapping")
InputConstants = JavaClass("com.mojang.blaze3d.platform.InputConstants")
Difficulty = JavaClass("net.minecraft.world.Difficulty")
BlockPos = JavaClass("net.minecraft.core.BlockPos")
SoundEvents = JavaClass("net.minecraft.sounds.SoundEvents")
SoundSource = JavaClass("net.minecraft.sounds.SoundSource")
LightLayer = JavaClass("net.minecraft.world.level.LightLayer")
